# Docker Compose configuration for QR Code Generator
# 
# This file defines the services needed to run the QR code generator application:
# - qr_code_app: The main Flask application
# - db: PostgreSQL database
# - pgadmin: PostgreSQL admin interface

version: '3.8'

services:
  qr_code_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - QR_CODE_DIR=/app/qr_codes
      - FILL_COLOR=red
      - BACK_COLOR=white
      - DATABASE_URL=postgresql://qruser:qrpassword@db:5432/qrdb
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - PYTHONPATH=/app
    volumes:
      - ./qr_codes:/app/qr_codes
      - ./logs:/app/logs
      - ./app:/app/app
      - migrations_data:/app/migrations
      - ./.env:/app/.env
    user: "${UID:-1000}:${GID:-1000}"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=qruser
      - POSTGRES_PASSWORD=qrpassword
      - POSTGRES_DB=qrdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data:
  migrations_data:
