name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: qruser
          POSTGRES_PASSWORD: qrpassword
          POSTGRES_DB: qrdb_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest

      - name: Initialize database and migrations
        env:
          DATABASE_URL: postgresql://qruser:qrpassword@localhost:5432/qrdb_test
          FLASK_APP: manage.py
        run: |
          mkdir -p migrations
          flask db init
          flask db migrate -m "Initial migration"
          flask db upgrade

      - name: Run tests
        env:
          DATABASE_URL: postgresql://qruser:qrpassword@localhost:5432/qrdb_test
          QR_CODE_DIR: qr_codes
          FLASK_ENV: testing
          PYTHONPATH: ${{ github.workspace }}
        run: |
          mkdir -p qr_codes
          pytest tests/ -v