name: Test QR Code Generator

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: qruser
          POSTGRES_PASSWORD: qrpassword
          POSTGRES_DB: qrdb_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r requirements.txt

      - name: Create QR codes directory
        run: mkdir -p qr_codes

      - name: Run tests
        env:
          DATABASE_URL: postgresql://qruser:qrpassword@localhost:5432/qrdb_test
          QR_CODE_DIR: qr_codes
          FILL_COLOR: red
          BACK_COLOR: white
          FLASK_ENV: testing
          TESTING: true
        run: |
          pytest tests/ -v